In [1]:
import tensorflow as tf
import pandas as pd
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

In [4]:
def Load_FileName(path): # 해당 폴더에 있는 모든 파일 이름들 불러오는 코드
    folder_list = os.listdir(path)
    XData = []
    p = 0
    for i in folder_list:
        file_list = os.listdir(path + '/' + i)
        for j in file_list:
            print(path + '/' + i + '/' + file_list[p])
            c = cv2.imread(path + '/' + i + '/' + file_list[p])
            c = cv2.cvtColor(c, cv2.COLOR_BGR2RGB)
            print(c.shape)
            XData.append(c) # Data_set 리스트 안에 사진 정보를 차례대로 넣는다
            p += 1
        p = 0
    print(np.array(XData))
    return np.array(XData)# 리스트를 배열화 시킨다.

def Make_Y(path, Y_list):
    folder_name = os.listdir(path)
    Y = []
    p = 0
    for i in folder_name:
        file_name = os.listdir(path+'/'+ i)
        for j in file_name:
            Y.append(Y_list[p])
            print(p)
        p += 1
    return np.array(Y)

In [5]:
X = Load_FileName('C:/Users/asdew32/Desktop/test/penguins')
# 테스트 데이터셋 가져오기

ValX = Load_FileName('C:/Users/asdew32/Desktop/test/validation')
# 검증을 위한 데이터셋

Y = Make_Y('C:/Users/asdew32/Desktop/test/penguins', ['A', 'B', 'C', 'D', 'E']) # 답지 데이터셋 만들기
ValY = Make_Y('C:/Users/asdew32/Desktop/test/validation', ['A', 'B', 'C', 'D', 'E']) # 검증을 위한 답지 데이터

# 왕관 펭귄 : 쇠푸른 펭귄 A, 왕관 펭귄 B, 황제 펭귄 C, 젠투 펭귄 D, 줄무늬 펭귄 E

Y = pd.get_dummies(Y) # 원 핫 인코딩
ValY = pd.get_dummies(ValY)
print(X.shape)
print(Y.shape)
print(ValX.shape)
print(ValY.shape)

C:/Users/asdew32/Desktop/test/penguins/blue_penguins/130_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/142_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/152_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/154_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/49_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1083197274-612x612.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1083968578-612x612.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1083969762-612x612.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1091157974-612x612.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1091158062-612x612.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/blue_penguins/istockphoto-1094745588-

(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/crown_penguins/images9.jpg
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/102_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/103_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/128_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/132_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/133_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/134_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/136_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/141_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/149_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor_penguins/157_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/emperor

(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/19_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/21_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/23_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/27_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/29_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/30_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/31_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/32_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/42_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/48_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/52_penguin.png
(227, 227, 3)
C:/Users/asdew32/Desktop/test/penguins/line_penguins/57_penguin.png
(227, 227, 3)
C:

[[[[ 79  93 104]
   [ 75  89 100]
   [ 75  89 100]
   ...
   [ 47  45  46]
   [ 38  36  37]
   [ 35  33  34]]

  [[117 131 142]
   [115 129 140]
   [113 127 138]
   ...
   [ 55  54  52]
   [ 48  46  47]
   [ 46  44  45]]

  [[133 146 155]
   [130 143 152]
   [130 143 152]
   ...
   [ 63  62  60]
   [ 58  57  55]
   [ 53  52  50]]

  ...

  [[132 113  96]
   [110  92  72]
   [113  94  77]
   ...
   [161 137 113]
   [159 135 111]
   [158 134 110]]

  [[113  94  77]
   [118  99  82]
   [114  95  78]
   ...
   [160 136 112]
   [159 135 111]
   [157 133 109]]

  [[120 101  84]
   [127 108  91]
   [116  97  80]
   ...
   [160 136 112]
   [158 134 110]
   [157 133 109]]]


 [[[ 79  93 104]
   [ 75  89 100]
   [ 75  89 100]
   ...
   [ 47  45  46]
   [ 38  36  37]
   [ 35  33  34]]

  [[117 131 142]
   [115 129 140]
   [113 127 138]
   ...
   [ 55  54  52]
   [ 48  46  47]
   [ 46  44  45]]

  [[133 146 155]
   [130 143 152]
   [130 143 152]
   ...
   [ 63  62  60]
   [ 58  57  55]
   [ 53  52

In [15]:
''' X_study = tf.keras.layers.Input(shape=[500,500,3])
H = tf.keras.layers.Conv2D(4, kernel_size=5, activation="relu")(X_study)
H = tf.keras.layers.MaxPooling2D()(H)
H = tf.keras.layers.Conv2D(8, kernel_size=3, activation="relu")(H)
H = tf.keras.layers.MaxPooling2D()(H)
H = tf.keras.layers.Flatten()(H)
H = tf.keras.layers.Dense(40, activation="relu")(H)
Y_study = tf.keras.layers.Dense(3, activation="softmax")(H)

model = tf.keras.models.Model(X_study, Y_study)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) '''

# 5개의 컨볼루션 3Dense층
studyX = tf.keras.layers.Input(shape=[227, 227, 3])

H = tf.keras.layers.Conv2D(96, kernel_size=11, strides=(4, 4), activation="relu")(studyX)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.MaxPool2D(pool_size=(3,3), strides=(2, 2))(H)

H = tf.keras.layers.Conv2D(256, kernel_size=5, padding="same", activation="relu")(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.MaxPool2D(pool_size=(3,3), strides=(2, 2))(H)

H = tf.keras.layers.Conv2D(384, kernel_size=3, padding="same", activation="relu")(H)

H = tf.keras.layers.Conv2D(384, kernel_size=3, padding="same", activation="relu")(H)

H = tf.keras.layers.Conv2D(256, kernel_size=3, padding="same", activation="relu")(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.MaxPool2D(pool_size=(3,3), strides=(2, 2))(H)

H = tf.keras.layers.Flatten()(H)
H = tf.keras.layers.Dense(4096, activation="relu")(H)
H = tf.keras.layers.Dense(4096, activation="relu")(H)
studyY = tf.keras.layers.Dense(5, activation="softmax")(H)

model = tf.keras.models.Model(studyX, studyY)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [26]:
model.fit(X, Y, epochs = 30, validation_data = (ValX, ValY))

Epoch 1/30
10/10 [==============================] - 18s 2s/step - loss: 0.1590 - accuracy: 0.9433 - val_loss: 5.6329 - val_accuracy: 0.3600
Epoch 2/30
10/10 [==============================] - 19s 2s/step - loss: 0.2365 - accuracy: 0.9500 - val_loss: 4.5519 - val_accuracy: 0.4667
Epoch 3/30
10/10 [==============================] - 18s 2s/step - loss: 0.1315 - accuracy: 0.9700 - val_loss: 5.0123 - val_accuracy: 0.4133
Epoch 4/30
10/10 [==============================] - 17s 2s/step - loss: 0.1262 - accuracy: 0.9667 - val_loss: 7.2191 - val_accuracy: 0.1733
Epoch 5/30
10/10 [==============================] - 17s 2s/step - loss: 0.1145 - accuracy: 0.9667 - val_loss: 6.6900 - val_accuracy: 0.3467
Epoch 6/30
10/10 [==============================] - 17s 2s/step - loss: 0.1387 - accuracy: 0.9600 - val_loss: 5.7807 - val_accuracy: 0.3333
Epoch 7/30
10/10 [==============================] - 21s 2s/step - loss: 0.1391 - accuracy: 0.9533 - val_loss: 6.4569 - val_accuracy: 0.2133
Epoch 8/30
10/10 [==

In [25]:
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 227, 227, 3)]     0         
                                                                 
 conv2d_20 (Conv2D)          (None, 55, 55, 96)        34944     
                                                                 
 batch_normalization_4 (Batc  (None, 55, 55, 96)       384       
 hNormalization)                                                 
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 27, 27, 96)       0         
 g2D)                                                            
                                                                 
 conv2d_21 (Conv2D)          (None, 27, 27, 256)       614656    
                                                                 
 batch_normalization_5 (Batc  (None, 27, 27, 256)      1024